**Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Upload the data**

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ML-EDA.csv to ML-EDA.csv

**Import the data**

In [3]:
Animal_data = pd.read_csv('ML-EDA.csv')
Animal_data
Animal_data.head(3)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1

In [ ]:
Animal_data.tail(2)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

**Shape() : number of rows,number of columns**

In [ ]:
Animal_data.shape

(205, 16)

**shape[0]:number of rows in dataset**

In [ ]:
print("number of all Animals =", Animal_data.shape[0])            # shape[0]:number of rows in dataset

number of all Animals = 205

**shape[1]:number of Columns in dataset**

In [ ]:
print("Number of all Animals = ", Animal_data.shape[1])

Number of all Animals =  16

In [ ]:
Animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [ ]:
Animal_data.dtypes

Animal                     object
Height (cm)                object
Weight (kg)                object
Color                      object
Lifespan (years)           object
Diet                       object
Habitat                    object
Predators                  object
Average Speed (km/h)       object
Countries Found            object
Conservation Status        object
Family                     object
Gestation Period (days)    object
Top Speed (km/h)           object
Social Structure           object
Offspring per Birth        object
dtype: object

In [ ]:
Animal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

In [ ]:
Animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [ ]:
Animal_d1 = Animal_data[['Animal','Height (cm)','Weight (kg)','Offspring per Birth']]
Animal_d1.head(6)

             Animal Height (cm) Weight (kg) Offspring per Birth
0          Aardvark     105-130       40-65                   1
1          Aardwolf       40-50        8-14                 2-5
2  African Elephant     270-310   2700-6000                   1
3      African Lion      80-110     120-250       2-4 (usually)
4  African Wild Dog       75-80       18-36               10-12
5       Alpine Ibex      67-101      19-120                   1

In [ ]:
Animal_d2 =  Animal_data[['Animal', 'Height (cm)','Weight (kg)', 'Color']]
Animal_d2.head(2)

     Animal Height (cm) Weight (kg)         Color
0  Aardvark     105-130       40-65          Grey
1  Aardwolf       40-50        8-14  Yellow-brown

In [ ]:
Animal_d2.to_csv('Modified-Animal-Dataset.csv')

**Drop/Delete column from data**

In [ ]:
animal_d3 = Animal_data.drop(columns=['Conservation Status','Social Structure'], axis=1)
animal_d3

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Family,Gestation Period (days),Top Speed (km/h),Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Orycteropodidae,210-240,40,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Hyaenidae,90,40,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Elephantidae,640-660,40,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Felidae,98-105,80,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Canidae,70,56,10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Bovidae,215-280,24,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Spheniscidae,80-90,25,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Kiwaidae,Not Applicable,Not Applicable,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Equidae,180-365,25,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Stegostomatidae,10-25,20,Up to 25

**Add New Column in Dataframe with Default Value**

In [ ]:
Animal_data['Dataset']= 'Animal_Type'
Animal_data

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth,Dataset
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Type
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Type
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Type
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Type
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50,Animal_Type
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1,Animal_Type
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable,Animal_Type
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20,Animal_Type
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25,Animal_Type

In [ ]:
Animal_data.columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth', 'Dataset'],
      dtype='object')

In [ ]:
col_dict = {'Animal': "Animal_name",
            'Height (cm)' :  "Height",
            'Weight (kg)' : "Weight",
             'Color' : "color",
            'Lifespan (years)' :"Years",
            'Diet' :"Diet",
            'Habitat' :"habbit",
            'Predators': "Hunters",
            'Average Speed (km/h)'  : "Speed",
              'Countries Found' : "Found Of countries",
            'Conservation Status': "Status",
            'Family' : "Family",
            'Gestation Period (days)': "Days",
            'Top Speed (km/h)': "High speed",
            'Social Structure' : "Structure",
            'Offspring per Birth' : "Birth",
            'Dataset' : "dataset1",}

In [ ]:
Animal_data = Animal_data.rename(columns = col_dict)
Animal_data.head(5)

,Animal_name,Height,Weight,color,Years,Diet,habbit,Hunters,Speed,Found Of countries,Status,Family,Days,High speed,Structure,Birth,dataset1
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Type
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Type
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Type
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Type
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Type

In [ ]:
Animal_data.select_dtypes(include = 'object').head()

,Animal_name,Height,Weight,color,Years,Diet,habbit,Hunters,Speed,Found Of countries,Status,Family,Days,High speed,Structure,Birth,dataset1
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Type
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Type
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Type
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Type
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Type

**Categorical Columns and Numerical Columns from data**

In [ ]:
Animal_data.select_dtypes(exclude = 'object').head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
categorical_col = Animal_data.select_dtypes(include = 'object').columns
categorical_col

Index(['Animal_name', 'Height', 'Weight', 'color', 'Years', 'Diet', 'habbit',
       'Hunters', 'Speed', 'Found Of countries', 'Status', 'Family', 'Days',
       'High speed', 'Structure', 'Birth', 'dataset1'],
      dtype='object')

In [ ]:
categorical_col = Animal_data.select_dtypes(exclude = 'object').columns
categorical_col

Index([], dtype='object')

In [ ]:
Animal_df = Categorical_col =Animal_data.select_dtypes(include = 'object')
Animal_df

,Animal_name,Height,Weight,color,Years,Diet,habbit,Hunters,Speed,Found Of countries,Status,Family,Days,High speed,Structure,Birth,dataset1
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Type
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Type
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Type
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Type
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50,Animal_Type
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1,Animal_Type
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable,Animal_Type
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20,Animal_Type
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25,Animal_Type

In [ ]:
num_df = Categorical_col = Animal_data.select_dtypes(exclude = 'object')
num_df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[205 rows x 0 columns]

In [ ]:
Categorical_col_List = list(Animal_data.select_dtypes(include = 'object').columns)
Categorical_col_List

['Animal_name',
 'Height',
 'Weight',
 'color',
 'Years',
 'Diet',
 'habbit',
 'Hunters',
 'Speed',
 'Found Of countries',
 'Status',
 'Family',
 'Days',
 'High speed',
 'Structure',
 'Birth',
 'dataset1']

In [ ]:
Numerical_col_List = list(Animal_data.select_dtypes(exclude = 'object').columns)
Numerical_col_List

[]

In [ ]:
Animal_data.duplicated().any()

np.False_

In [ ]:
Animal_data.duplicated().any()

np.False_

In [ ]:
Animal_data.head(20)

,Animal_name,Height,Weight,color,Years,Diet,habbit,Hunters,Speed,Found Of countries,Status,Family,Days,High speed,Structure,Birth,dataset1
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1,Animal_Type
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5,Animal_Type
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1,Animal_Type
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually),Animal_Type
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12,Animal_Type
5,Alpine Ibex,67-101,19-120,Brown,15-20,Herbivore,"Mountains, Alpine","Wolves, Golden Eagles",56-64,European Alps,Least Concern,Bovidae,150,56-64,Group-based,1,Animal_Type
6,Amazon Rainforest Frog,2-13,Up to 0.5,Various,4-17,Insectivore,Amazon Rainforest,"Birds, Snakes",0.1-1,Amazon Rainforest,Not Evaluated,Dendrobatidae,10-15,0.8,Solitary,Up to 40,Animal_Type
7,American Bison,152-186,"318-1,000",Brown,15-20,Herbivore,"Grasslands, Plains","Wolves, Grizzly Bears",40-56,North America,Near Threatened,Bovidae,270-290,56,Group-based,1,Animal_Type
8,Anteater,52-91,22-41,"Brown, White",15-20,Insectivore,"Grasslands, Forests","Jaguars, Pumas",24,Central and South America,Least Concern,Myrmecophagidae,190-210,24,Solitary,1,Animal_Type
9,Arabian Horse,140-160,380-1000,Various,25-30,Herbivore,"Middle East, North Africa","Humans, Predators",65,"Middle East, North Africa",Not Applicable,Equidae,330-342,65,Herd-based,1,Animal_Type
10,Arabian Oryx,70-90,65-90,White,10-20,Herbivore,Desert,"Lions, Leopards",55,Middle East,Vulnerable,Bovidae,210-240,55,Herd-based,1,Animal_Type
11,Arctic Fox,25-30,2.5-9,White,3-6,Omnivore,Tundra,Polar Bears,60,Arctic regions,Least Concern,Canidae,52-60,60,Solitary,4-11,Animal_Type
12,Arowana,Up to 120,Up to 6.7,"Silver, Gold, Green",10-20,"Carnivore, Piscivore","Freshwater Rivers, Lakes","Birds, Larger Fish",16-32,"South America, Asia",Not Evaluated,Osteoglossidae,Not Applicable,32,Solitary,Not Applicable,Animal_Type
13,Asian Elephant,200-300,2000-5000,Grey,60-80,Herbivore,"Grasslands, Forests","Tigers, Leopards",40,Asia (Southeast),Endangered,Elephantidae,640-660,40,Herd-based,1,Animal_Type
14,Atlantic Puffin,25-30,500-620,"Black, White",20-25,"Carnivore, Piscivore","North Atlantic, Arctic","Gulls, Birds of Prey",30-50,"North Atlantic, Arctic",Vulnerable,Alcidae,40,80,Colony-based,1,Animal_Type
15,Atlantic Spotted Dolphin,200-250,120-140,"Gray, White",20-25,Carnivore,"Oceans, Coastal Areas","Sharks, Orcas",40-64,Worldwide,Least Concern,Delphinidae,360-380,40-64,Group-based,1,Animal_Type
16,Australian Fur Seal,112-160,18-40,"Brown, Gray",14-17,Carnivore,Coastal Waters,"Sharks, Orcas",24-40,"Australia, New Zealand",Least Concern,Otariidae,300-350,24-40,Group-based,1,Animal_Type
17,Axolotl,Up to 30,Up to 300,Various,10-15,Carnivore,"Lakes, Canals","Fish, Birds",0.8,Mexico,Critically Endangered,Ambystomatidae,14-21,0.2-0.3,Solitary,100-300,Animal_Type
18,Aye-Aye,35-37,2.2-2.7,"Black, Brown",20-23,"Omnivore, Insectivore",Rainforests,Birds of Prey,32,Madagascar,Endangered,Daubentoniidae,160-170,32,Solitary,1,Animal_Type
19,Baird's Tapir,76-107,150-400,"Brown, Black",25-30,Herbivore,"Rainforests, Grasslands","Jaguars, Crocodiles",48,Central and South America,Endangered,Tapiridae,390-395,48,Solitary,1,Animal_Type

In [ ]:
Animal_data[Animal_data.duplicated()]

Empty DataFrame
Columns: [Animal_name, Height, Weight, color, Years, Diet, habbit, Hunters, Speed, Found Of countries, Status, Family, Days, High speed, Structure, Birth, dataset1]
Index: []

In [ ]:
Animal_d2 = Animal_data.drop_duplicates()

In [ ]:
Animal_d2.shape

(205, 17)

In [ ]:
# Indexing columns
df = Animal_d2.isnull().sum().reset_index()
#Rename columns
df.columns = ['column','null_records']
#Create new column gind out null value percentage
df['% null_records'] = (df['null_records']/11199)*100
df

                column  null_records  % null_records
0          Animal_name             0             0.0
1               Height             0             0.0
2               Weight             0             0.0
3                color             0             0.0
4                Years             0             0.0
5                 Diet             0             0.0
6               habbit             0             0.0
7              Hunters             0             0.0
8                Speed             0             0.0
9   Found Of countries             0             0.0
10              Status             0             0.0
11              Family             0             0.0
12                Days             0             0.0
13          High speed             0             0.0
14           Structure             0             0.0
15               Birth             0             0.0
16            dataset1             0             0.0

In [ ]:
Animal_d2['Diet']

0      Insectivore
1      Insectivore
2        Herbivore
3        Carnivore
4        Carnivore
          ...
200      Herbivore
201      Carnivore
202       Omnivore
203      Herbivore
204      Carnivore
Name: Diet, Length: 205, dtype: object

In [ ]:
mode_fueltype = Animal_d2['Diet'].mode()[0]
mode_fueltype

'Carnivore'

In [ ]:
Animal_d2['Diet'] = Animal_d2['Diet'].fillna(mode_fueltype)

In [ ]:
Animal_d2.isnull().sum()

Animal_name           0
Height                0
Weight                0
color                 0
Years                 0
Diet                  0
habbit                0
Hunters               0
Speed                 0
Found Of countries    0
Status                0
Family                0
Days                  0
High speed            0
Structure             0
Birth                 0
dataset1              0
dtype: int64

In [ ]:
Animal_d2.isnull().sum()

Animal_name           0
Height                0
Weight                0
color                 0
Years                 0
Diet                  0
habbit                0
Hunters               0
Speed                 0
Found Of countries    0
Status                0
Family                0
Days                  0
High speed            0
Structure             0
Birth                 0
dataset1              0
dtype: int64