**import the Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Upload the data**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Dataset-1.csv to Dataset-1.csv

**Import the data**

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the uploaded file name
car_data = pd.read_csv('Dataset-1.csv')
car_data

#Display First 5 rows
car_data.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [ ]:
car_data.tail(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [ ]:
car_data.shape   #(rows [0th indexing position], colums[1st indexing position])

(11914, 16)

In [ ]:
print("number of rows =", car_data.shape[0])

number of rows = 11914

In [ ]:
print("number of columns = ", car_data.shape[1])

number of columns =  16

In [ ]:
### List of columns / features

In [ ]:
car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [ ]:
car_data.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [ ]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [ ]:
car_tab1 = car_data[['Make','Model','Year','MSRP']]
car_tab1.head(6)

  Make       Model  Year   MSRP
0  BMW  1 Series M  2011  46135
1  BMW    1 Series  2011  40650
2  BMW    1 Series  2011  36350
3  BMW    1 Series  2011  29450
4  BMW    1 Series  2011  34500
5  BMW    1 Series  2012  31200

In [ ]:
car_tab2 =  car_data[['Make','Model','Year','highway MPG','city mpg', 'Popularity','MSRP']]
car_tab2.head(2)

  Make       Model  Year  highway MPG  city mpg  Popularity   MSRP
0  BMW  1 Series M  2011           26        19        3916  46135
1  BMW    1 Series  2011           28        19        3916  40650

In [ ]:
car_tab2.to_csv('Modified-Car-Dataset.csv')

**Drop/Delete column from data frame**

In [ ]:
car_tab3 = car_data.drop(columns=['Market Category', 'Popularity'], axis = 1)
car_tab3

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Vehicle Size,Vehicle Style,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,26,19,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,19,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,20,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,18,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,18,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,26,17,28995

**Add New Column in Dataframe with Default Value**

In [ ]:
car_tab3['Dataset']= 'Car_Dataset'
car_tab3

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Vehicle Size,Vehicle Style,highway MPG,city mpg,MSRP,Dataset
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,26,19,46135,Car_Dataset
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,19,40650,Car_Dataset
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,20,36350,Car_Dataset
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,18,29450,Car_Dataset
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,18,34500,Car_Dataset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,46120,Car_Dataset
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,56670,Car_Dataset
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50620,Car_Dataset
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,50920,Car_Dataset
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,26,17,28995,Car_Dataset

In [ ]:
car_data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [ ]:
col_dict = {'Engine Fuel Type' : "Fuel_Type",
             'Engine HP': 'Engine_HP',
            'Engine Cylinders' : 'No_of_Cylinders',
            'Transmission Type' : 'Transmission_Type',
            'Number of Doors' :'No_of_Doors',
            'Market Category'  : 'Market_Category',
            'Vehicle Size' : 'Vehical_Size',
            'Vehicle Style' : 'vehical_Style',
            'highway MPG' : 'Highway_MPG',
            'city mpg' : 'City_MPG',
            'MSRP': 'Car_Price'}

In [ ]:
car_data = car_data.rename(columns = col_dict)
car_data.head(5)

,Make,Model,Year,Fuel_Type,Engine_HP,No_of_Cylinders,Transmission_Type,Driven_Wheels,No_of_Doors,Market_Category,Vehical_Size,vehical_Style,Highway_MPG,City_MPG,Popularity,Car_Price
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [ ]:
car_data.select_dtypes(include = 'object').head()

,Make,Model,Fuel_Type,Transmission_Type,Driven_Wheels,Market_Category,Vehical_Size,vehical_Style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible

**Categorical Columns and Numerical Columns from data**

In [ ]:
car_data.select_dtypes(exclude = 'object').head()

,Year,Engine_HP,No_of_Cylinders,No_of_Doors,Highway_MPG,City_MPG,Popularity,Car_Price
0,2011,335.0,6.0,2.0,26,19,3916,46135
1,2011,300.0,6.0,2.0,28,19,3916,40650
2,2011,300.0,6.0,2.0,28,20,3916,36350
3,2011,230.0,6.0,2.0,28,18,3916,29450
4,2011,230.0,6.0,2.0,28,18,3916,34500

In [ ]:
categorical_col = car_data.select_dtypes(include = 'object').columns
categorical_col

Index(['Make', 'Model', 'Fuel_Type', 'Transmission_Type', 'Driven_Wheels',
       'Market_Category', 'Vehical_Size', 'vehical_Style'],
      dtype='object')

In [ ]:
categorical_col = car_data.select_dtypes(exclude = 'object').columns
categorical_col

Index(['Year', 'Engine_HP', 'No_of_Cylinders', 'No_of_Doors', 'Highway_MPG',
       'City_MPG', 'Popularity', 'Car_Price'],
      dtype='object')

In [ ]:
cat_df = Categorical_col =car_data.select_dtypes(include = 'object')
cat_df

,Make,Model,Fuel_Type,Transmission_Type,Driven_Wheels,Market_Category,Vehical_Size,vehical_Style
0,BMW,1 Series M,premium unleaded (required),MANUAL,rear wheel drive,"Factory Tuner,Luxury,High-Performance",Compact,Coupe
1,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Convertible
2,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,High-Performance",Compact,Coupe
3,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,"Luxury,Performance",Compact,Coupe
4,BMW,1 Series,premium unleaded (required),MANUAL,rear wheel drive,Luxury,Compact,Convertible
...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11910,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11911,Acura,ZDX,premium unleaded (required),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11912,Acura,ZDX,premium unleaded (recommended),AUTOMATIC,all wheel drive,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback
11913,Lincoln,Zephyr,regular unleaded,AUTOMATIC,front wheel drive,Luxury,Midsize,Sedan

In [ ]:
num_df = Categorical_col = car_data.select_dtypes(exclude = 'object')
num_df

,Year,Engine_HP,No_of_Cylinders,No_of_Doors,Highway_MPG,City_MPG,Popularity,Car_Price
0,2011,335.0,6.0,2.0,26,19,3916,46135
1,2011,300.0,6.0,2.0,28,19,3916,40650
2,2011,300.0,6.0,2.0,28,20,3916,36350
3,2011,230.0,6.0,2.0,28,18,3916,29450
4,2011,230.0,6.0,2.0,28,18,3916,34500
...,...,...,...,...,...,...,...,...
11909,2012,300.0,6.0,4.0,23,16,204,46120
11910,2012,300.0,6.0,4.0,23,16,204,56670
11911,2012,300.0,6.0,4.0,23,16,204,50620
11912,2013,300.0,6.0,4.0,23,16,204,50920
11913,2006,221.0,6.0,4.0,26,17,61,28995

In [ ]:
Categorical_col_List = list(car_data.select_dtypes(include = 'object').columns)
Categorical_col_List

['Make',
 'Model',
 'Fuel_Type',
 'Transmission_Type',
 'Driven_Wheels',
 'Market_Category',
 'Vehical_Size',
 'vehical_Style']

In [ ]:
Numerical_col_List = list(car_data.select_dtypes(exclude = 'object').columns)
Numerical_col_List

['Year',
 'Engine_HP',
 'No_of_Cylinders',
 'No_of_Doors',
 'Highway_MPG',
 'City_MPG',
 'Popularity',
 'Car_Price']

**Check Data Discrepencies**
1) Duplicate Records 2) Missing Values

In [ ]:
# Check for duplicate records
car_data.duplicated().any()

np.True_

In [ ]:
# Number of duplicate records i.e.,duplicate rows
car_data.duplicated().any()

np.True_

In [ ]:
car_data.head(20)

,Make,Model,Year,Fuel_Type,Engine_HP,No_of_Cylinders,Transmission_Type,Driven_Wheels,No_of_Doors,Market_Category,Vehical_Size,vehical_Style,Highway_MPG,City_MPG,Popularity,Car_Price
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
9,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200
10,BMW,1 Series,2013,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39600
11,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
12,BMW,1 Series,2013,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,44400
13,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,19,3916,37200
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
15,BMW,1 Series,2013,premium unleaded (required),320.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,25,18,3916,48250
16,BMW,1 Series,2013,premium unleaded (required),320.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,43550
17,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000

In [ ]:
# Display the duplicate records
car_data[car_data.duplicated()]

,Make,Model,Year,Fuel_Type,Engine_HP,No_of_Cylinders,Transmission_Type,Driven_Wheels,No_of_Doors,Market_Category,Vehical_Size,vehical_Style,Highway_MPG,City_MPG,Popularity,Car_Price
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

In [ ]:
# Remove/Delete Duplicate Records

In [ ]:
car_data2 = car_data.drop_duplicates()   # is a clean datasets now

In [ ]:
car_data2.shape

(11199, 16)

In [ ]:
# Indexing columns
df = car_data2.isnull().sum().reset_index()
#Rename columns
df.columns = ['column','null_records']
#Create new column gind out null value percentage
df['% null_records'] = (df['null_records']/11199)*100
df

               column  null_records  % null_records
0                Make             0        0.000000
1               Model             0        0.000000
2                Year             0        0.000000
3           Fuel_Type             0        0.000000
4           Engine_HP             0        0.000000
5     No_of_Cylinders            30        0.267881
6   Transmission_Type             0        0.000000
7       Driven_Wheels             0        0.000000
8         No_of_Doors             6        0.053576
9     Market_Category          3376       30.145549
10       Vehical_Size             0        0.000000
11      vehical_Style             0        0.000000
12        Highway_MPG             0        0.000000
13           City_MPG             0        0.000000
14         Popularity             0        0.000000
15          Car_Price             0        0.000000

In [ ]:
car_data2['Fuel_Type']

0           premium unleaded (required)
1           premium unleaded (required)
2           premium unleaded (required)
3           premium unleaded (required)
4           premium unleaded (required)
                      ...
11909       premium unleaded (required)
11910       premium unleaded (required)
11911       premium unleaded (required)
11912    premium unleaded (recommended)
11913                  regular unleaded
Name: Fuel_Type, Length: 11199, dtype: object

In [ ]:
mode_fueltype = car_data2['Fuel_Type'].mode()[0]
mode_fueltype

'regular unleaded'

In [ ]:
## Frequency of categories column
car_data2['Fuel_Type'].value_counts()

Fuel_Type
regular unleaded                                6658
premium unleaded (required)                     1956
premium unleaded (recommended)                  1392
flex-fuel (unleaded/E85)                         887
diesel                                           150
electric                                          66
flex-fuel (premium unleaded required/E85)         53
flex-fuel (premium unleaded recommended/E85)      26
flex-fuel (unleaded/natural gas)                   6
natural gas                                        2
Name: count, dtype: int64

In [ ]:
car_data2['Make'].value_counts()

Make
Chevrolet        1083
Ford              825
Toyota            719
Volkswagen        568
Nissan            551
Dodge             529
GMC               482
Honda             433
Mazda             412
Cadillac          396
Suzuki            342
Mercedes-Benz     341
Infiniti          328
BMW               324
Audi              321
Volvo             266
Hyundai           259
Acura             246
Subaru            239
Kia               229
Mitsubishi        208
Lexus             202
Buick             190
Chrysler          187
Pontiac           181
Lincoln           160
Land Rover        139
Porsche           136
Oldsmobile        132
Saab              109
Aston Martin       91
Bentley            74
Plymouth           71
Ferrari            69
FIAT               62
Scion              60
Maserati           55
Lamborghini        52
Rolls-Royce        31
Lotus              28
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Genesis             3
Bugatti             3
Spyker              2
Name: count, dtype: int64

In [ ]:
car_data2['Fuel_Type'] = car_data2['Fuel_Type'].fillna(mode_fueltype)

/tmp/ipykernel_24324/340058365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car_data2['Fuel_Type'] = car_data2['Fuel_Type'].fillna(mode_fueltype)

In [ ]:
car_data2.isnull().sum()

Make                    0
Model                   0
Year                    0
Fuel_Type               0
Engine_HP              69
No_of_Cylinders        30
Transmission_Type       0
Driven_Wheels           0
No_of_Doors             6
Market_Category      3376
Vehical_Size            0
vehical_Style           0
Highway_MPG             0
City_MPG                0
Popularity              0
Car_Price               0
dtype: int64

In [ ]:
hp_mean = car_data2['Engine_HP'].mean()
hp_mean

np.float64(253.38885893980233)

In [ ]:
car_data2['Engine_HP'] = car_data2['Engine_HP'].fillna(hp_mean)

/tmp/ipykernel_24324/1856510687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car_data2['Engine_HP'] = car_data2['Engine_HP'].fillna(hp_mean)

In [ ]:
car_data2.isnull().sum()

Make                    0
Model                   0
Year                    0
Fuel_Type               0
Engine_HP               0
No_of_Cylinders        30
Transmission_Type       0
Driven_Wheels           0
No_of_Doors             6
Market_Category      3376
Vehical_Size            0
vehical_Style           0
Highway_MPG             0
City_MPG                0
Popularity              0
Car_Price               0
dtype: int64